name: Pythomata Continuous Integration pipeline.

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install tox
    - name: Safety Check
      run:  tox -e safety
    - name: License Check
      run:  tox -e liccheck
    - name: Code style check
      run: |
        tox -e black-check
        tox -e flake8
    - name: Static type check
      run: tox -e mypy
    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }}
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        yml: ./codecov.yml
#        fail_ci_if_error: true
    - name: Generate Documentation
      run: tox -e docs

